import Head from 'next/head';
import Home from "./home";
import axios from 'axios';

export default function Index({kategoriList, productList}) {
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

        <link 
        rel="preconnect" 
        href="https://fonts.googleapis.com"
        />
        
        <link 
        rel="preconnect" 
        href="https://fonts.gstatic.com" 
        crossOrigin="true"
        />

      </Head>
     
      <Home kategoriList = {kategoriList} productList={productList}/>
     

    </div>
  )
}

export const getServerSideProps = async (context) => {
  const res = await axios.get(`${process.env.NEXT_PUBLIC_API_URL}/kategoriler`)
  const prdct = await axios.get(`${process.env.NEXT_PUBLIC_API_URL}/products`)
  
  return {
    props: {
      kategoriList: res.data ? res.data : [],
      productList: prdct.data ? prdct.data : [],
    },
  }
}


